# stack.yaml

resolver: lts-14.27

nix:
#   enable:   true # Uncomment for nix on non-NixOS OS
    packages: [ mesa_noglu.drivers
                libGL
                libGLU
                freeglut
              ]

packages:
- .
